# 配置文件

DAILY_TIME: "14:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2020-12-17" # 纪念日
CITY: "北京"

BIRTHDAY:
  - "03-16"

APP_ID: "wxc4110feaf9a656c4"
APP_SECRET: "bc976967f026552316a473f9edf7cea1"

USER_ID: 
  - "oSitk6qCIZHz3VKoJNpZMxrPC8Ms"
TEMPLATE_ID: "1Bbs-O7i8E2P-UsnuSiLnma3FXp9JtiWUPKkQt1gAIg"
